### PR TITLE
fix: VerifyExpiresAt

### PR DESCRIPTION
**Pull request by matteosilv**
VerifyExpiresAt does not do what is expected from its description

### CODE REVIEW

**Comment by oxisto** [comment]
I am not quite sure if I understand you correctly. The description says `VerifyExpiresAt compares the exp claim against cmp (cmp < exp).` Which we do by only using `Before`.

**Comment by matteosilv** [comment]
> I am not quite sure if I understand you correctly. The description says `VerifyExpiresAt compares the exp claim against cmp (cmp < exp).` Which we do by only using `Before`.

It isn't correct documentation states <=

https://github.com/golang-jwt/jwt/blob/main/map_claims.go#L35

**Comment by oxisto** [comment]
> > I am not quite sure if I understand you correctly. The description says `VerifyExpiresAt compares the exp claim against cmp (cmp < exp).` Which we do by only using `Before`.
> 
> It isn't correct documentation states <=
> 
> https://github.com/golang-jwt/jwt/blob/main/map_claims.go#L35

Ah, it seams the documentation for MapClaims says <= and for StandardClaims it says <.

From a logical point of view I would say that < is correct because at the time of exp it is already expired. The additional leeway we can grant is another story. I will double check with the RFC later.

**Comment by matteosilv** [comment]
VerifyExpiresAt should verify that at the provided time the token is going to be expired. Is this assumption right?

**Comment by oxisto** [comment]
> VerifyExpiresAt should verify that at the provided time the token is going to be expired. Is this assumption right?

No. It checks whether the token is *not yet expired*. I agree that we should probably make the documentation of these functions clearer.

**Comment by matteosilv** [comment]
In this case, I agree that strict < is correct. The name of the method and its description however are not clear enough imho

**Comment by oxisto** [comment]
Superseded by #234

**Pull request closed without merging**
